/**
 * Ski resort webcam configuration (North America focus).
 * - type: 'image' — direct snapshot URL (auto-refreshed)
 * - type: 'iframe' — embedded live page (Roundshot, YouTube, etc.)
 * - mountain — groups cams for powder ranking (one snow score per mountain)
 * - home: true — optional; force this cam as the homepage hero for that mountain
 *   (otherwise homepage picks the first non–snow-stake cam per mountain)
 *
 * Full US catalog (including mountains without cams) is mountains-catalog.js.
 * To attach a feed later, add a cam here whose `mountain` name matches the catalog.
 *
 * Brownrice snapshots: https://player.brownrice.com/snapshot/{streamName}
 * WEATHER: lat/long → Open-Meteo powder radar + 7-day forecast.
 */
export const RESORTS = [
  // —— Colorado ——
  {
    id: 'vail-back-bowls',
    home: true,
    name: 'Vail — The Back Bowls',
    mountain: 'Vail',
    url: 'https://player.brownrice.com/snapshot/vailch21',
    type: 'image',
    region: 'Colorado',
    provider: 'Brownrice',
    latitude: 39.6403,
    longitude: -106.3742,
  },
  {
    id: 'vail-blue-sky',
    name: 'Vail — Blue Sky Basin',
    mountain: 'Vail',
    url: 'https://player.brownrice.com/snapshot/vailbluesky',
    type: 'image',
    region: 'Colorado',
    provider: 'Brownrice',
    latitude: 39.6403,
    longitude: -106.3742,
  },
  {
    id: 'vail-eagles-nest',
    name: 'Vail — Eagle’s Nest',
    mountain: 'Vail',
    url: 'https://player.brownrice.com/snapshot/vaileaglesnest',
    type: 'image',
    region: 'Colorado',
    provider: 'Brownrice',
    latitude: 39.6403,
    longitude: -106.3742,
  },
  {
    id: 'vail-lionshead',
    name: 'Vail — Lionshead Village',
    mountain: 'Vail',
    url: 'https://player.brownrice.com/snapshot/lionsheadvillage',
    type: 'image',
    region: 'Colorado',
    provider: 'Town of Vail',
    latitude: 39.6435,
    longitude: -106.3875,
  },
  {
    id: 'beaver-creek-spruce',
    home: true,
    name: 'Beaver Creek — Spruce Saddle',
    mountain: 'Beaver Creek',
    url: 'https://player.brownrice.com/snapshot/bcspruce',
    type: 'image',
    region: 'Colorado',
    provider: 'Brownrice',
    latitude: 39.6042,
    longitude: -106.5165,
  },
  {
    id: 'keystone-river-run',
    name: 'Keystone — River Run',
    mountain: 'Keystone',
    url: 'https://player.brownrice.com/snapshot/keystoneriverrun',
    type: 'image',
    region: 'Colorado',
    provider: 'Brownrice',
    latitude: 39.6069,
    longitude: -105.9542,
  },
  {
    id: 'keystone-north-peak',
    home: true,
    name: 'Keystone — North Peak',
    mountain: 'Keystone',
    url: 'https://player.brownrice.com/snapshot/keystonenorthpeak',
    type: 'image',
    region: 'Colorado',
    provider: 'Brownrice',
    latitude: 39.6069,
    longitude: -105.9542,
  },
  {
    id: 'crested-butte-base',
    home: true,
    name: 'Crested Butte — Base',
    mountain: 'Crested Butte',
    url: 'https://player.brownrice.com/snapshot/crestedbuttebase',
    type: 'image',
    region: 'Colorado',
    provider: 'Brownrice',
    latitude: 38.8997,
    longitude: -106.9658,
  },
  {
    id: 'aspen-highland-bowl',
    home: true,
    name: 'Aspen — Highland Bowl',
    mountain: 'Aspen',
    url: 'https://backend.roundshot.com/cams/3d9af2719f79f6c4447593172a4f5c6a/medium',
    type: 'image',
    region: 'Colorado',
    provider: 'Roundshot',
    latitude: 39.1867,
    longitude: -106.8175,
  },
  {
    id: 'aspen-maroon-bells',
    name: 'Aspen — Maroon Bells',
    mountain: 'Aspen',
    url: 'https://backend.roundshot.com/cams/19a0db224d24e8f0b9f874eeb6b18a9a/medium',
    type: 'image',
    region: 'Colorado',
    provider: 'Roundshot',
    latitude: 39.1867,
    longitude: -106.8175,
  },
  {
    id: 'aspen-roundshot',
    name: 'Aspen Mountain — Roundshot',
    mountain: 'Aspen',
    url: 'https://aspen.roundshot.com/aspen/',
    type: 'iframe',
    region: 'Colorado',
    provider: 'Roundshot',
    latitude: 39.1867,
    longitude: -106.8175,
  },
  {
    id: 'aspen-highlands-roundshot',
    name: 'Aspen Highlands — Roundshot',
    mountain: 'Aspen',
    url: 'https://aspen.roundshot.com/highlands/',
    type: 'iframe',
    region: 'Colorado',
    provider: 'Roundshot',
    latitude: 39.182,
    longitude: -106.855,
  },
  {
    id: 'aspen-buttermilk-roundshot',
    name: 'Buttermilk — Roundshot',
    mountain: 'Aspen',
    url: 'https://aspen.roundshot.com/buttermilk/',
    type: 'iframe',
    region: 'Colorado',
    provider: 'Roundshot',
    latitude: 39.208,
    longitude: -106.86,
  },
  {
    id: 'aspen-snowmass-sams-knob',
    name: 'Snowmass — Sam’s Knob',
    mountain: 'Aspen',
    url: 'https://aspen.roundshot.com/snowmass-samsknob',
    type: 'iframe',
    region: 'Colorado',
    provider: 'Roundshot',
    latitude: 39.209,
    longitude: -106.949,
  },
  {
    id: 'arapaho-basin-base',
    name: 'Arapahoe Basin — Base Area',
    mountain: 'Arapahoe Basin',
    url: 'https://ftp.purchus.io/wwwroot/abasin/webcam/abasincam1001m.jpg',
    type: 'image',
    region: 'Colorado',
    provider: 'A-Basin',
    latitude: 39.6425,
    longitude: -105.8717,
  },
  {
    id: 'arapaho-basin-zuma',
    home: true,
    name: 'Arapahoe Basin — Zuma',
    mountain: 'Arapahoe Basin',
    url: 'https://ftp.purchus.io/wwwroot/abasin/webcam/abasincam5.jpg',
    type: 'image',
    region: 'Colorado',
    provider: 'A-Basin',
    latitude: 39.6425,
    longitude: -105.8717,
  },
  {
    id: 'copper-center-village',
    home: true,
    name: 'Copper Mountain — Center Village',
    mountain: 'Copper Mountain',
    url: 'https://manage.hdrelay.com/snapshot/59703a85-67d3-4825-9f33-b8244569af43?size=1082x614&f=60000',
    type: 'image',
    region: 'Colorado',
    provider: 'HDRelay',
    latitude: 39.5022,
    longitude: -106.1497,
  },
  {
    id: 'copper-super-bee',
    name: 'Copper Mountain — Super Bee',
    mountain: 'Copper Mountain',
    url: 'https://manage.hdrelay.com/snapshot/0a21617e-b513-4f3a-999a-4ba0896b9df4?size=1082x614&f=60000',
    type: 'image',
    region: 'Colorado',
    provider: 'HDRelay',
    latitude: 39.5022,
    longitude: -106.1497,
  },
  {
    id: 'copper-excelerator',
    name: 'Copper Mountain — Excelerator',
    mountain: 'Copper Mountain',
    url: 'https://manage.hdrelay.com/snapshot/0d6c3cf7-c523-41cf-9e01-0019ed77f9a3?size=1082x614&f=60000',
    type: 'image',
    region: 'Colorado',
    provider: 'HDRelay',
    latitude: 39.5022,
    longitude: -106.1497,
  },
  {
    id: 'copper-union-peak',
    name: 'Copper Mountain — Union Peak',
    mountain: 'Copper Mountain',
    url: 'https://manage.hdrelay.com/snapshot/73c252b4-e74a-47fa-b8ea-5a34f0b6469a?size=1082x614&f=60000',
    type: 'image',
    region: 'Colorado',
    provider: 'HDRelay',
    latitude: 39.5022,
    longitude: -106.1497,
  },
  {
    id: 'copper-aerie',
    name: 'Copper Mountain — Aerie',
    mountain: 'Copper Mountain',
    url: 'https://manage.hdrelay.com/snapshot/671bcfb507697ecebbaffc13?size=1082x614&f=60000',
    type: 'image',
    region: 'Colorado',
    provider: 'HDRelay',
    latitude: 39.5022,
    longitude: -106.1497,
  },
  {
    id: 'copper-woodward',
    name: 'Copper Mountain — Woodward Terrain Park',
    mountain: 'Copper Mountain',
    url: 'https://manage.hdrelay.com/snapshot/faba06d4-a3e9-4caf-93a8-8fc61e573958?size=1082x614&f=60000',
    type: 'image',
    region: 'Colorado',
    provider: 'HDRelay',
    latitude: 39.5022,
    longitude: -106.1497,
  },
  {
    id: 'copper-snowstake',
    name: 'Copper Mountain — Snow Stake',
    mountain: 'Copper Mountain',
    url: 'https://manage.hdrelay.com/snapshot/fb469125-f1f3-459f-aeb4-98cb674e395f?size=1082x614&f=60000',
    type: 'image',
    region: 'Colorado',
    provider: 'HDRelay',
    latitude: 39.5022,
    longitude: -106.1497,
  },
  {
    id: 'breckenridge-peak8-from-peak9',
    home: true,
    name: 'Breckenridge — Peak 8 from Peak 9',
    mountain: 'Breckenridge',
    url: 'https://player.brownrice.com/snapshot/breckenridge9',
    type: 'image',
    region: 'Colorado',
    provider: 'Brownrice',
    latitude: 39.4817,
    longitude: -106.0384,
  },
  {
    id: 'breckenridge-peak9',
    name: 'Breckenridge — Peak 9',
    mountain: 'Breckenridge',
    url: 'https://player.brownrice.com/snapshot/breckenridge10',
    type: 'image',
    region: 'Colorado',
    provider: 'Brownrice',
    latitude: 39.4817,
    longitude: -106.0384,
  },
  {
    id: 'breckenridge-peak8-base',
    name: 'Breckenridge — Peak 8 Base',
    mountain: 'Breckenridge',
    url: 'https://manage.hdrelay.com/snapshot/f16d8cb6-a15c-4d74-9ce8-3fc8bfc08168?size=1082x614&f=60000',
    type: 'image',
    region: 'Colorado',
    provider: 'HDRelay',
    latitude: 39.4817,
    longitude: -106.0384,
  },
  {
    id: 'breckenridge-peak8-live',
    name: 'Breckenridge — Peak 8 Live',
    mountain: 'Breckenridge',
    url: 'https://www.youtube.com/embed/mHTTPNYltZo?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Colorado',
    provider: 'YouTube',
    latitude: 39.4817,
    longitude: -106.0384,
  },
  {
    id: 'steamboat-square',
    name: 'Steamboat — Square Cam',
    mountain: 'Steamboat',
    url: 'https://www.youtube.com/embed/2UJDLWcSADk?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Colorado',
    provider: 'YouTube',
    latitude: 40.4572,
    longitude: -106.8045,
  },
  {
    id: 'steamboat-thunderhead',
    home: true,
    name: 'Steamboat — Thunderhead',
    mountain: 'Steamboat',
    url: 'https://www.youtube.com/embed/nfTQNv3jdSQ?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Colorado',
    provider: 'YouTube',
    latitude: 40.4572,
    longitude: -106.8045,
  },
  {
    id: 'winter-park-base',
    home: true,
    name: 'Winter Park — Base Cam',
    mountain: 'Winter Park',
    url: 'https://www.youtube.com/embed/vyWAzJAWv4w?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Colorado',
    provider: 'YouTube',
    latitude: 39.8868,
    longitude: -105.7625,
  },
  {
    id: 'winter-park-snow-stake',
    name: 'Winter Park — Snow Stake',
    mountain: 'Winter Park',
    url: 'https://www.youtube.com/embed/_wOIgFEMypY?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Colorado',
    provider: 'YouTube',
    latitude: 39.8868,
    longitude: -105.7625,
  },
  {
    id: 'telluride-revelation',
    name: 'Telluride — Revelation Bowl 360',
    mountain: 'Telluride',
    url: 'https://tellurideskiresort.roundshot.com/',
    type: 'iframe',
    region: 'Colorado',
    provider: 'Roundshot',
    latitude: 37.9375,
    longitude: -107.8123,
  },
  {
    id: 'telluride-see-forever',
    home: true,
    name: 'Telluride — See Forever',
    mountain: 'Telluride',
    url: 'https://g1.ipcamlive.com/player/snapshot.php?alias=jointpoint',
    type: 'image',
    region: 'Colorado',
    provider: 'IPCamLive',
    latitude: 37.9375,
    longitude: -107.8123,
  },
  {
    id: 'telluride-black-iron',
    name: 'Telluride — Black Iron Bowl',
    mountain: 'Telluride',
    url: 'https://g1.ipcamlive.com/player/snapshot.php?alias=bonvivant',
    type: 'image',
    region: 'Colorado',
    provider: 'IPCamLive',
    latitude: 37.9375,
    longitude: -107.8123,
  },
  {
    id: 'telluride-village',
    name: 'Telluride — Mountain Village',
    mountain: 'Telluride',
    url: 'https://g1.ipcamlive.com/player/snapshot.php?alias=plazacam',
    type: 'image',
    region: 'Colorado',
    provider: 'IPCamLive',
    latitude: 37.9375,
    longitude: -107.8123,
  },

  // —— California / Nevada (Tahoe) ——
  {
    id: 'heavenly-tram',
    home: true,
    name: 'Heavenly — Tram',
    mountain: 'Heavenly',
    url: 'https://player.brownrice.com/snapshot/heavenlytram',
    type: 'image',
    region: 'California',
    provider: 'Brownrice',
    latitude: 38.9353,
    longitude: -119.9395,
  },
  {
    id: 'heavenly-midstation',
    name: 'Heavenly — Mid Station',
    mountain: 'Heavenly',
    url: 'https://player.brownrice.com/snapshot/heavenlymidstation',
    type: 'image',
    region: 'California',
    provider: 'Brownrice',
    latitude: 38.9353,
    longitude: -119.9395,
  },
  {
    id: 'northstar-pluto',
    name: 'Northstar — Pluto',
    mountain: 'Northstar',
    url: 'https://player.brownrice.com/snapshot/northstarspluto',
    type: 'image',
    region: 'California',
    provider: 'Brownrice',
    latitude: 39.2746,
    longitude: -120.1211,
  },
  {
    id: 'northstar-village',
    home: true,
    name: 'Northstar — Village',
    mountain: 'Northstar',
    url: 'https://player.brownrice.com/snapshot/northstarvillage',
    type: 'image',
    region: 'California',
    provider: 'Brownrice',
    latitude: 39.2746,
    longitude: -120.1211,
  },
  {
    id: 'palisades-alpine',
    home: true,
    name: 'Palisades Tahoe — Alpine',
    mountain: 'Palisades Tahoe',
    url: 'https://palisadestahoe.roundshot.com/alpine/',
    type: 'iframe',
    region: 'California',
    provider: 'Roundshot',
    latitude: 39.197,
    longitude: -120.2356,
  },
  {
    id: 'palisades-silverado',
    name: 'Palisades Tahoe — Silverado',
    mountain: 'Palisades Tahoe',
    url: 'https://palisadestahoe.roundshot.com/silverado/',
    type: 'iframe',
    region: 'California',
    provider: 'Roundshot',
    latitude: 39.197,
    longitude: -120.2356,
  },
  {
    id: 'mammoth-unbound',
    name: 'Mammoth — Unbound Main Park',
    mountain: 'Mammoth Mountain',
    url: 'https://media.mammothresorts.com/mmsa/mammoth/cams/Unbound_Main_Park_1_1280x720.jpg',
    type: 'image',
    region: 'California',
    provider: 'Mammoth Resorts',
    latitude: 37.6308,
    longitude: -119.0326,
  },
  {
    id: 'mammoth-top-sierra',
    home: true,
    name: 'Mammoth — Top of Sierra',
    mountain: 'Mammoth Mountain',
    url: 'https://media.mammothresorts.com/mmsa/mammoth/cams/Top_Of_Sierra_1_1280x720.jpg',
    type: 'image',
    region: 'California',
    provider: 'Mammoth Resorts',
    latitude: 37.6308,
    longitude: -119.0326,
  },

  // —— Utah ——
  {
    id: 'alta-collins',
    home: true,
    name: 'Alta — Top of Collins / Ballroom',
    mountain: 'Alta',
    url: 'https://www.skiutah.com/files/blob/webcam/1229833423',
    type: 'image',
    region: 'Utah',
    provider: 'Ski Utah',
    latitude: 40.5883,
    longitude: -111.6378,
  },
  {
    id: 'snowbird-hidden-peak',
    home: true,
    name: 'Snowbird — Hidden Peak 360',
    mountain: 'Snowbird',
    url: 'https://snowbird.roundshot.com/tv',
    type: 'iframe',
    region: 'Utah',
    provider: 'Roundshot',
    latitude: 40.583,
    longitude: -111.657,
  },
  {
    id: 'solitude-snow-stake',
    home: true,
    name: 'Solitude — Snow Stake',
    mountain: 'Solitude',
    url: 'https://www.skiutah.com/files/blob/webcam/525820161',
    type: 'image',
    region: 'Utah',
    provider: 'Ski Utah',
    latitude: 40.6198,
    longitude: -111.5933,
  },
  {
    id: 'solitude-powderhorn',
    name: 'Solitude — Powderhorn',
    mountain: 'Solitude',
    url: 'https://www.youtube.com/embed/fKLVbvQhPsc?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Utah',
    provider: 'YouTube',
    latitude: 40.6198,
    longitude: -111.5933,
  },
  {
    id: 'solitude-sunshine-bowl',
    name: 'Solitude — Sunshine Bowl',
    mountain: 'Solitude',
    url: 'https://www.youtube.com/embed/Lnznapxh2xM?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Utah',
    provider: 'YouTube',
    latitude: 40.6198,
    longitude: -111.5933,
  },
  {
    id: 'brighton-milly',
    home: true,
    name: 'Brighton — Milly Express',
    mountain: 'Brighton',
    url: 'https://www.skiutah.com/files/blob/webcam/JmrFbmFNyhrLnjcNJpjLNe',
    type: 'image',
    region: 'Utah',
    provider: 'Ski Utah',
    latitude: 40.598,
    longitude: -111.5832,
  },
  {
    id: 'brighton-crest-top',
    name: 'Brighton — Crest Chair (top)',
    mountain: 'Brighton',
    url: 'https://www.skiutah.com/files/blob/webcam/JCtjLqqZBMbFm2N74oPbga',
    type: 'image',
    region: 'Utah',
    provider: 'Ski Utah',
    latitude: 40.598,
    longitude: -111.5832,
  },
  {
    id: 'brighton-snowstake',
    name: 'Brighton — Snow Stake',
    mountain: 'Brighton',
    url: 'https://www.skiutah.com/files/blob/webcam/LBSKmCQHw9GVGF5AcHnE2o',
    type: 'image',
    region: 'Utah',
    provider: 'Ski Utah',
    latitude: 40.598,
    longitude: -111.5832,
  },
  {
    id: 'park-city-summit',
    name: 'Park City — Summit House',
    mountain: 'Park City',
    url: 'https://www.skiutah.com/files/blob/webcam/2101381068',
    type: 'image',
    region: 'Utah',
    provider: 'Ski Utah',
    latitude: 40.6514,
    longitude: -111.508,
  },
  {
    id: 'park-city-lookout',
    home: true,
    name: 'Park City — Lookout Cabin',
    mountain: 'Park City',
    url: 'https://www.skiutah.com/files/blob/webcam/1011920804',
    type: 'image',
    region: 'Utah',
    provider: 'Ski Utah',
    latitude: 40.6514,
    longitude: -111.508,
  },
  {
    id: 'park-city-canyons-stake',
    name: 'Park City — Canyons Snow Stake',
    mountain: 'Park City',
    url: 'https://www.skiutah.com/files/blob/webcam/HwPWjHBpohRksnjfPUxMng',
    type: 'image',
    region: 'Utah',
    provider: 'Ski Utah',
    latitude: 40.6834,
    longitude: -111.5552,
  },
  {
    id: 'deer-valley-snow-park',
    home: true,
    name: 'Deer Valley — Snow Park Lodge',
    mountain: 'Deer Valley',
    url: 'https://www.youtube.com/embed/E7Hh7Q6qIKk?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Utah',
    provider: 'YouTube',
    latitude: 40.6374,
    longitude: -111.4783,
  },
  {
    id: 'deer-valley-silver-lake',
    name: 'Deer Valley — Silver Lake Lodge',
    mountain: 'Deer Valley',
    url: 'https://www.youtube.com/embed/uE_ent5rC3Y?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Utah',
    provider: 'YouTube',
    latitude: 40.6374,
    longitude: -111.4783,
  },
  {
    id: 'deer-valley-empire',
    name: 'Deer Valley — Empire Express',
    mountain: 'Deer Valley',
    url: 'https://www.youtube.com/embed/r8qiPv9XCOM?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Utah',
    provider: 'YouTube',
    latitude: 40.6374,
    longitude: -111.4783,
  },
  {
    id: 'deer-valley-ruby',
    name: 'Deer Valley — Ruby Express',
    mountain: 'Deer Valley',
    url: 'https://www.youtube.com/embed/iNdfTLilLlU?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Utah',
    provider: 'YouTube',
    latitude: 40.6374,
    longitude: -111.4783,
  },
  {
    id: 'deer-valley-galena',
    name: 'Deer Valley — Galena Express',
    mountain: 'Deer Valley',
    url: 'https://www.youtube.com/embed/0shWeR7Fvpg?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Utah',
    provider: 'YouTube',
    latitude: 40.6374,
    longitude: -111.4783,
  },
  {
    id: 'deer-valley-revelator',
    name: 'Deer Valley — Revelator Express',
    mountain: 'Deer Valley',
    url: 'https://www.youtube.com/embed/XZjubaPbamE?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Utah',
    provider: 'YouTube',
    latitude: 40.6374,
    longitude: -111.4783,
  },
  {
    id: 'deer-valley-jordanelle',
    name: 'Deer Valley — Jordanelle View',
    mountain: 'Deer Valley',
    url: 'https://www.skiutah.com/files/blob/webcam/1473199274',
    type: 'image',
    region: 'Utah',
    provider: 'Ski Utah',
    latitude: 40.6374,
    longitude: -111.4783,
  },
  {
    id: 'snowbasin-snowstake',
    name: 'Snowbasin — Snow Stake',
    mountain: 'Snowbasin',
    url: 'https://www.skiutah.com/files/blob/webcam/548931577',
    type: 'image',
    region: 'Utah',
    provider: 'Ski Utah',
    latitude: 41.216,
    longitude: -111.8569,
  },
  {
    id: 'snowbasin-john-paul',
    home: true,
    name: 'Snowbasin — John Paul',
    mountain: 'Snowbasin',
    url: 'https://www.skiutah.com/files/blob/webcam/140020919',
    type: 'image',
    region: 'Utah',
    provider: 'Ski Utah',
    latitude: 41.216,
    longitude: -111.8569,
  },
  {
    id: 'snowbasin-earls',
    name: "Snowbasin — Earl's Plaza",
    mountain: 'Snowbasin',
    url: 'https://www.skiutah.com/files/blob/webcam/1536047841',
    type: 'image',
    region: 'Utah',
    provider: 'Ski Utah',
    latitude: 41.216,
    longitude: -111.8569,
  },

  // —— New Mexico ——
  {
    id: 'taos-base',
    name: 'Taos — Base',
    mountain: 'Taos Ski Valley',
    url: 'https://player.brownrice.com/snapshot/tsv',
    type: 'image',
    region: 'New Mexico',
    provider: 'Brownrice',
    latitude: 36.5957,
    longitude: -105.4505,
  },
  {
    id: 'taos-highline',
    name: 'Taos — Highline Ridge',
    mountain: 'Taos Ski Valley',
    url: 'https://player.brownrice.com/snapshot/tsvridge',
    type: 'image',
    region: 'New Mexico',
    provider: 'Brownrice',
    latitude: 36.5957,
    longitude: -105.4505,
  },
  {
    id: 'taos-kachina',
    home: true,
    name: 'Taos — Kachina Peak',
    mountain: 'Taos Ski Valley',
    url: 'https://player.brownrice.com/snapshot/tsvlonestar',
    type: 'image',
    region: 'New Mexico',
    provider: 'Brownrice',
    latitude: 36.5957,
    longitude: -105.4505,
  },

  // —— Wyoming ——
  {
    id: 'jackson-hole-teewinot',
    home: true,
    name: 'Jackson Hole — Teewinot',
    mountain: 'Jackson Hole',
    url: 'https://cams.jacksonhole.com/webcam/teewinot.jpg',
    type: 'image',
    region: 'Wyoming',
    provider: 'Jackson Hole',
    latitude: 43.5875,
    longitude: -110.8278,
  },
  {
    id: 'jackson-hole-tram-station',
    name: 'Jackson Hole — Tram Station',
    mountain: 'Jackson Hole',
    url: 'https://cams.jacksonhole.com/webcam/trambase.jpg',
    type: 'image',
    region: 'Wyoming',
    provider: 'Jackson Hole',
    latitude: 43.5875,
    longitude: -110.8278,
  },
  {
    id: 'jackson-hole-summit-still',
    name: 'Jackson Hole — Summit',
    mountain: 'Jackson Hole',
    url: 'https://backend.roundshot.com/cams/12a4b2c24cd515e0a115d4a0f59ef7f8/medium',
    type: 'image',
    region: 'Wyoming',
    provider: 'Roundshot',
    latitude: 43.5875,
    longitude: -110.8278,
  },
  {
    id: 'jackson-hole-rendezvous-still',
    name: 'Jackson Hole — Rendezvous',
    mountain: 'Jackson Hole',
    url: 'https://backend.roundshot.com/cams/6f7dc91857e22fe329e8bdeef5ee5750/medium',
    type: 'image',
    region: 'Wyoming',
    provider: 'Roundshot',
    latitude: 43.5875,
    longitude: -110.8278,
  },
  {
    id: 'jackson-hole-summit',
    name: 'Jackson Hole — Summit 360',
    mountain: 'Jackson Hole',
    url: 'https://jacksonhole.roundshot.com/summit/',
    type: 'iframe',
    region: 'Wyoming',
    provider: 'Roundshot',
    latitude: 43.5875,
    longitude: -110.8278,
  },
  {
    id: 'jackson-hole-casper',
    name: 'Jackson Hole — Casper 360',
    mountain: 'Jackson Hole',
    url: 'https://jacksonhole.roundshot.com/casper/',
    type: 'iframe',
    region: 'Wyoming',
    provider: 'Roundshot',
    latitude: 43.5875,
    longitude: -110.8278,
  },
  {
    id: 'jackson-hole-bridger',
    name: 'Jackson Hole — Bridger 360',
    mountain: 'Jackson Hole',
    url: 'https://jacksonhole.roundshot.com/bridger/',
    type: 'iframe',
    region: 'Wyoming',
    provider: 'Roundshot',
    latitude: 43.5875,
    longitude: -110.8278,
  },

  // —— Montana ——
  {
    id: 'big-sky-lone-peak-tram',
    home: true,
    name: 'Big Sky — Lone Peak Tram',
    mountain: 'Big Sky',
    url: 'https://camstreamer.com/embed/hcsmYlCWjirEU86zfXwaFGyX7w6GL3xJ3M3TkbZf?enablejsapi=1&rel=0&modestbranding=1&playsinline=1',
    type: 'iframe',
    region: 'Montana',
    provider: 'Camstreamer',
    latitude: 45.285,
    longitude: -111.4017,
  },
  {
    id: 'big-sky-everetts-8800',
    name: 'Big Sky — Everett’s 8800',
    mountain: 'Big Sky',
    url: 'https://camstreamer.com/embed/dmy0fkeL3LXtkQnzlK5Td1QrVGSt08aM8IVVmE08?enablejsapi=1&rel=0&modestbranding=1&playsinline=1',
    type: 'iframe',
    region: 'Montana',
    provider: 'Camstreamer',
    latitude: 45.285,
    longitude: -111.4017,
  },
  {
    id: 'big-sky-golf-course',
    name: 'Big Sky — Golf Course',
    mountain: 'Big Sky',
    url: 'https://camstreamer.com/embed/bvRmCc5qmXcMEJ02xMlIAL4cg3291Tfj0pzIp9tW?enablejsapi=1&rel=0&modestbranding=1&playsinline=1',
    type: 'iframe',
    region: 'Montana',
    provider: 'Camstreamer',
    latitude: 45.285,
    longitude: -111.4017,
  },

  // —— Idaho ——
  {
    id: 'sun-valley-white-clouds',
    home: true,
    name: 'Sun Valley — White Clouds',
    mountain: 'Sun Valley',
    url: 'https://storage.googleapis.com/prism-cam-00052/1080-watermark.jpg',
    type: 'image',
    region: 'Idaho',
    provider: 'Prism',
    latitude: 43.6807,
    longitude: -114.3518,
  },
  {
    id: 'sun-valley-bowls',
    name: 'Sun Valley — The Bowls',
    mountain: 'Sun Valley',
    url: 'https://b9.hdrelay.com/camera/390488dd-a758-4dd3-ae95-91c408abbff0/snapshot',
    type: 'image',
    region: 'Idaho',
    provider: 'HDRelay',
    latitude: 43.6807,
    longitude: -114.3518,
  },
  {
    id: 'sun-valley-river-run',
    name: 'Sun Valley — River Run',
    mountain: 'Sun Valley',
    url: 'https://b9.hdrelay.com/camera/4c82abd4-5ef5-4b16-870f-548c2885d3f0/snapshot',
    type: 'image',
    region: 'Idaho',
    provider: 'HDRelay',
    latitude: 43.6807,
    longitude: -114.3518,
  },
  {
    id: 'sun-valley-warm-springs',
    name: 'Sun Valley — Warm Springs',
    mountain: 'Sun Valley',
    url: 'https://b9.hdrelay.com/camera/5f27e4b8-7c51-4451-bcf5-3ab843f56bc6/snapshot',
    type: 'image',
    region: 'Idaho',
    provider: 'HDRelay',
    latitude: 43.6807,
    longitude: -114.3518,
  },
  {
    id: 'sun-valley-snowstake',
    name: 'Sun Valley — Snow Stake',
    mountain: 'Sun Valley',
    url: 'https://b9.hdrelay.com/camera/9d9a56b7-bf9e-4162-be9c-06c42ca208ff/snapshot',
    type: 'image',
    region: 'Idaho',
    provider: 'HDRelay',
    latitude: 43.6807,
    longitude: -114.3518,
  },

  // —— Oregon ——
  {
    id: 'mt-bachelor-mid-mountain',
    home: true,
    name: 'Mt. Bachelor — Mid Mountain',
    mountain: 'Mt. Bachelor',
    url: 'https://www.youtube.com/embed/qjfPiDu9F50?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Oregon',
    provider: 'YouTube (Mt. Bachelor)',
    latitude: 43.9794,
    longitude: -121.6889,
  },
  {
    id: 'mt-bachelor-cloudchaser',
    name: 'Mt. Bachelor — Cloudchaser',
    mountain: 'Mt. Bachelor',
    url: 'https://www.youtube.com/embed/EaICEj8hgZk?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Oregon',
    provider: 'YouTube (Mt. Bachelor)',
    latitude: 43.9794,
    longitude: -121.6889,
  },
  {
    id: 'mt-bachelor-snow-stake',
    name: 'Mt. Bachelor — Snow Stake',
    mountain: 'Mt. Bachelor',
    url: 'https://www.youtube.com/embed/jF9f7hsdlJg?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Oregon',
    provider: 'YouTube (Mt. Bachelor)',
    latitude: 43.9794,
    longitude: -121.6889,
  },
  {
    id: 'mt-bachelor-outback',
    name: 'Mt. Bachelor — Top of Outback',
    mountain: 'Mt. Bachelor',
    url: 'https://api.mtbachelor.com/api/v1/cams/mtn/12',
    type: 'image',
    region: 'Oregon',
    provider: 'Mt. Bachelor',
    latitude: 43.9794,
    longitude: -121.6889,
  },
  {
    id: 'mt-bachelor-sunrise-top',
    name: 'Mt. Bachelor — Top of Sunrise',
    mountain: 'Mt. Bachelor',
    url: 'https://api.mtbachelor.com/api/v1/cams/mtn/8',
    type: 'image',
    region: 'Oregon',
    provider: 'Mt. Bachelor',
    latitude: 43.9794,
    longitude: -121.6889,
  },
  {
    id: 'mt-bachelor-pine-marten-base',
    name: 'Mt. Bachelor — Pine Marten Base',
    mountain: 'Mt. Bachelor',
    url: 'https://api.mtbachelor.com/api/v1/cams/mtn/1',
    type: 'image',
    region: 'Oregon',
    provider: 'Mt. Bachelor',
    latitude: 43.9794,
    longitude: -121.6889,
  },
  {
    id: 'mt-bachelor-cone',
    name: 'Mt. Bachelor — The Cone',
    mountain: 'Mt. Bachelor',
    url: 'https://api.mtbachelor.com/api/v1/cams/mtn/3',
    type: 'image',
    region: 'Oregon',
    provider: 'Mt. Bachelor',
    latitude: 43.9794,
    longitude: -121.6889,
  },
  {
    id: 'mt-bachelor-sunrise-base',
    name: 'Mt. Bachelor — Sunrise Base',
    mountain: 'Mt. Bachelor',
    url: 'https://api.mtbachelor.com/api/v1/cams/mtn/5',
    type: 'image',
    region: 'Oregon',
    provider: 'Mt. Bachelor',
    latitude: 43.9794,
    longitude: -121.6889,
  },

  // —— Washington ——
  {
    id: 'stevens-pass-jupiter',
    home: true,
    name: 'Stevens Pass — Jupiter',
    mountain: 'Stevens Pass',
    url: 'https://player.brownrice.com/snapshot/stevenspassjupiter',
    type: 'image',
    region: 'Washington',
    provider: 'Brownrice',
    latitude: 47.746,
    longitude: -121.088,
  },
  {
    id: 'stevens-pass-snowstake',
    name: 'Stevens Pass — Snow Stake',
    mountain: 'Stevens Pass',
    url: 'https://player.brownrice.com/snapshot/stevenspasssnowstake',
    type: 'image',
    region: 'Washington',
    provider: 'Brownrice',
    latitude: 47.746,
    longitude: -121.088,
  },
  {
    id: 'crystal-summit-360',
    home: true,
    name: 'Crystal Mountain — Summit 360',
    mountain: 'Crystal Mountain',
    url: 'https://crystalmountainresort.roundshot.com/cams/1011',
    type: 'image',
    region: 'Washington',
    provider: 'Roundshot',
    latitude: 46.9354,
    longitude: -121.4749,
  },
  {
    id: 'crystal-midway-panorama',
    name: 'Crystal Mountain — Midway Panorama',
    mountain: 'Crystal Mountain',
    url: 'https://crystalmountainresort.roundshot.com/cams/1022',
    type: 'image',
    region: 'Washington',
    provider: 'Roundshot',
    latitude: 46.9354,
    longitude: -121.4749,
  },
  {
    id: 'crystal-summit-roundshot',
    name: 'Crystal Mountain — Summit Roundshot',
    mountain: 'Crystal Mountain',
    url: 'https://crystalmountainresort.roundshot.com/summit/',
    type: 'iframe',
    region: 'Washington',
    provider: 'Roundshot',
    latitude: 46.9354,
    longitude: -121.4749,
  },

  // —— Alberta (SkiBig3: Lake Louise, Banff Sunshine, Mt. Norquay) ——
  {
    id: 'lake-louise-1',
    home: true,
    name: 'Lake Louise — Gondola Top',
    mountain: 'Lake Louise',
    url: 'https://cams.skilouise.com/cam1.jpg',
    type: 'image',
    region: 'Alberta',
    provider: 'Lake Louise',
    latitude: 51.4254,
    longitude: -116.1773,
  },
  {
    id: 'lake-louise-2',
    name: 'Lake Louise — Base Area',
    mountain: 'Lake Louise',
    url: 'https://cams.skilouise.com/cam2.jpg',
    type: 'image',
    region: 'Alberta',
    provider: 'Lake Louise',
    latitude: 51.4254,
    longitude: -116.1773,
  },
  {
    id: 'lake-louise-3',
    name: 'Lake Louise — Ptarmigan',
    mountain: 'Lake Louise',
    url: 'https://cams.skilouise.com/cam3.jpg',
    type: 'image',
    region: 'Alberta',
    provider: 'Lake Louise',
    latitude: 51.4254,
    longitude: -116.1773,
  },
  {
    id: 'lake-louise-5',
    name: 'Lake Louise — Ptarmigan Top Distant',
    mountain: 'Lake Louise',
    url: 'https://cams.skilouise.com/cam5.jpg',
    type: 'image',
    region: 'Alberta',
    provider: 'Lake Louise',
    latitude: 51.4254,
    longitude: -116.1773,
  },
  {
    id: 'lake-louise-paradise',
    name: 'Lake Louise — Paradise',
    mountain: 'Lake Louise',
    url: 'https://cams.skilouise.com/cam8.jpg',
    type: 'image',
    region: 'Alberta',
    provider: 'Lake Louise',
    latitude: 51.4254,
    longitude: -116.1773,
  },
  {
    id: 'banff-sunshine-strawberry',
    home: true,
    name: 'Banff Sunshine — Strawberry Express',
    mountain: 'Banff Sunshine',
    url: 'https://cameras.skibanff.com/dynamic/14m',
    type: 'image',
    region: 'Alberta',
    provider: 'Banff Sunshine',
    latitude: 51.0783,
    longitude: -115.7786,
  },
  {
    id: 'banff-sunshine-standish',
    name: 'Banff Sunshine — Standish Express',
    mountain: 'Banff Sunshine',
    url: 'https://cameras.skibanff.com/dynamic/15m',
    type: 'image',
    region: 'Alberta',
    provider: 'Banff Sunshine',
    latitude: 51.0783,
    longitude: -115.7786,
  },
  {
    id: 'banff-sunshine-aurora',
    name: 'Banff Sunshine — Aurora Cam',
    mountain: 'Banff Sunshine',
    url: 'https://cameras.skibanff.com/dynamic/10m',
    type: 'image',
    region: 'Alberta',
    provider: 'Banff Sunshine',
    latitude: 51.0783,
    longitude: -115.7786,
  },
  {
    id: 'banff-sunshine-assiniboine',
    name: 'Banff Sunshine — Mount Assiniboine',
    mountain: 'Banff Sunshine',
    url: 'https://cameras.skibanff.com/dynamic/17m',
    type: 'image',
    region: 'Alberta',
    provider: 'Banff Sunshine',
    latitude: 51.0783,
    longitude: -115.7786,
  },
  {
    id: 'mt-norquay-cascade',
    home: true,
    name: 'Mt. Norquay — Cascade',
    mountain: 'Mt. Norquay',
    url: 'https://banffnorquay.com/webcam-images/winter/CascadeCam/cascade.jpg',
    type: 'image',
    region: 'Alberta',
    provider: 'Mt. Norquay',
    latitude: 51.2047,
    longitude: -115.5986,
  },
  {
    id: 'mt-norquay-sundance',
    name: 'Mt. Norquay — Sundance',
    mountain: 'Mt. Norquay',
    url: 'https://banffnorquay.com/webcam-images/winter/SundanceCam/sundance.jpg',
    type: 'image',
    region: 'Alberta',
    provider: 'Mt. Norquay',
    latitude: 51.2047,
    longitude: -115.5986,
  },

  // —— British Columbia ——
  {
    id: 'whistler-roundhouse',
    name: 'Whistler — Roundhouse Lodge',
    mountain: 'Whistler Blackcomb',
    url: 'https://player.brownrice.com/snapshot/whistlerroundhouse',
    type: 'image',
    region: 'British Columbia',
    provider: 'Brownrice',
    latitude: 50.1163,
    longitude: -122.9574,
  },
  {
    id: 'whistler-peak',
    home: true,
    name: 'Whistler — Peak',
    mountain: 'Whistler Blackcomb',
    url: 'https://player.brownrice.com/snapshot/whistlerpeak',
    type: 'image',
    region: 'British Columbia',
    provider: 'Brownrice',
    latitude: 50.1163,
    longitude: -122.9574,
  },
  {
    id: 'whistler-creekside',
    name: 'Whistler — Creekside',
    mountain: 'Whistler Blackcomb',
    url: 'https://player.brownrice.com/snapshot/whistlercreekside',
    type: 'image',
    region: 'British Columbia',
    provider: 'Brownrice',
    latitude: 50.1163,
    longitude: -122.9574,
  },
  {
    id: 'whistler-blackcomb',
    name: 'Blackcomb — Base',
    mountain: 'Whistler Blackcomb',
    url: 'https://player.brownrice.com/snapshot/whistlerblackcomb',
    type: 'image',
    region: 'British Columbia',
    provider: 'Brownrice',
    latitude: 50.1163,
    longitude: -122.9574,
  },
  {
    id: 'whistler-7th-heaven',
    name: 'Blackcomb — 7th Heaven',
    mountain: 'Whistler Blackcomb',
    url: 'https://player.brownrice.com/snapshot/whistler7thheaven',
    type: 'image',
    region: 'British Columbia',
    provider: 'Brownrice',
    latitude: 50.1163,
    longitude: -122.9574,
  },
  {
    id: 'kicking-horse-top',
    home: true,
    name: 'Kicking Horse — Top (Stairway)',
    mountain: 'Kicking Horse',
    url: 'https://secure.skircr.com/cams/khcam5/stairway.jpg',
    type: 'image',
    region: 'British Columbia',
    provider: 'Kicking Horse',
    latitude: 51.2992,
    longitude: -117.0536,
  },
  {
    id: 'kicking-horse-base',
    name: 'Kicking Horse — Base',
    mountain: 'Kicking Horse',
    url: 'https://secure.skircr.com/cams/khcam2/basecam.jpg',
    type: 'image',
    region: 'British Columbia',
    provider: 'Kicking Horse',
    latitude: 51.2992,
    longitude: -117.0536,
  },
  {
    id: 'revelstoke-village',
    name: 'Revelstoke — Village',
    mountain: 'Revelstoke',
    url: 'https://relay.ozolio.com/pub.api?cmd=embed&oid=EMB_PVWK000010B0',
    type: 'iframe',
    region: 'British Columbia',
    provider: 'Ozolio',
    latitude: 50.9581,
    longitude: -118.1637,
  },
  {
    id: 'revelstoke-skywalk',
    name: 'Revelstoke — Skywalk',
    mountain: 'Revelstoke',
    url: 'https://relay.ozolio.com/pub.api?cmd=embed&oid=EMB_SCDV000013E4',
    type: 'iframe',
    region: 'British Columbia',
    provider: 'Ozolio',
    latitude: 50.9581,
    longitude: -118.1637,
  },
  {
    id: 'revelstoke-stoke',
    name: 'Revelstoke — Top of Stoke Chair',
    mountain: 'Revelstoke',
    url: 'https://relay.ozolio.com/pub.api?cmd=embed&oid=EMB_KPMC000010BF',
    type: 'iframe',
    region: 'British Columbia',
    provider: 'Ozolio',
    latitude: 50.9581,
    longitude: -118.1637,
  },
  {
    id: 'revelstoke-upper-gondola',
    home: true,
    name: 'Revelstoke — Top of Upper Gondola',
    mountain: 'Revelstoke',
    url: 'https://relay.ozolio.com/pub.api?cmd=embed&oid=EMB_NDZZ000010B5',
    type: 'iframe',
    region: 'British Columbia',
    provider: 'Ozolio',
    latitude: 50.9581,
    longitude: -118.1637,
  },

  // —— Quebec ——
  {
    id: 'tremblant-summit',
    home: true,
    name: 'Tremblant — Summit',
    mountain: 'Tremblant',
    url: 'https://tremblantwebcams.com/sommet.jpg',
    type: 'image',
    region: 'Quebec',
    provider: 'Tremblant',
    latitude: 46.2124,
    longitude: -74.5846,
  },
  {
    id: 'tremblant-south-base',
    name: 'Tremblant — South Base',
    mountain: 'Tremblant',
    url: 'https://tremblantwebcams.com/meteomedia6.jpg',
    type: 'image',
    region: 'Quebec',
    provider: 'Tremblant',
    latitude: 46.2124,
    longitude: -74.5846,
  },
  {
    id: 'tremblant-st-bernard',
    name: 'Tremblant — Place St-Bernard',
    mountain: 'Tremblant',
    url: 'https://tremblantwebcams.com/meteomedia5.jpg',
    type: 'image',
    region: 'Quebec',
    provider: 'Tremblant',
    latitude: 46.2124,
    longitude: -74.5846,
  },
  {
    id: 'tremblant-voyageurs',
    name: 'Tremblant — Place des Voyageurs',
    mountain: 'Tremblant',
    url: 'https://tremblantwebcams.com/meteomedia8.jpg',
    type: 'image',
    region: 'Quebec',
    provider: 'Tremblant',
    latitude: 46.2124,
    longitude: -74.5846,
  },

  // —— Vermont ——
  {
    id: 'stowe-village',
    home: true,
    name: 'Stowe — Village',
    mountain: 'Stowe',
    url: 'https://player.brownrice.com/snapshot/stowevillage',
    type: 'image',
    region: 'Vermont',
    provider: 'Brownrice',
    latitude: 44.5313,
    longitude: -72.7814,
  },
  {
    id: 'mount-snow-base',
    home: true,
    name: 'Mount Snow — Base',
    mountain: 'Mount Snow',
    url: 'https://player.brownrice.com/snapshot/mountsnowbase',
    type: 'image',
    region: 'Vermont',
    provider: 'Brownrice',
    latitude: 42.9084,
    longitude: -72.8637,
  },
  {
    id: 'sugarbush',
    home: true,
    name: 'Sugarbush — Gate House',
    mountain: 'Sugarbush',
    url: 'https://www.youtube.com/embed/jhCh3dsEv-M?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Vermont',
    provider: 'YouTube',
    latitude: 44.1353,
    longitude: -72.9084,
  },
  {
    id: 'stratton-summit',
    home: true,
    name: 'Stratton — Summit',
    mountain: 'Stratton',
    url: 'https://www.youtube.com/embed/9E00W9R_Cnc?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Vermont',
    provider: 'YouTube',
    latitude: 43.1134,
    longitude: -72.9082,
  },
  {
    id: 'stratton-mid-mountain',
    name: 'Stratton — Mid Mountain',
    mountain: 'Stratton',
    url: 'https://www.youtube.com/embed/AhcH03HwuH0?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Vermont',
    provider: 'YouTube',
    latitude: 43.1134,
    longitude: -72.9082,
  },
  {
    id: 'stratton-snowbowl',
    name: 'Stratton — Snow Bowl',
    mountain: 'Stratton',
    url: 'https://www.youtube.com/embed/ildHe_RG1Mk?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Vermont',
    provider: 'YouTube',
    latitude: 43.1134,
    longitude: -72.9082,
  },
  {
    id: 'stratton-base',
    name: 'Stratton — Main Base',
    mountain: 'Stratton',
    url: 'https://www.youtube.com/embed/H-_sGi4Sbtk?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Vermont',
    provider: 'YouTube',
    latitude: 43.1134,
    longitude: -72.9082,
  },
  {
    id: 'jaypeak',
    home: true,
    name: 'Jay Peak — Tramside',
    mountain: 'Jay Peak',
    url: 'https://b15.hdrelay.com/camera/6526fd5a071b19b5189bb07b/snapshot',
    type: 'image',
    region: 'Vermont',
    provider: 'HDRelay',
    latitude: 44.937,
    longitude: -72.5079,
  },
  {
    id: 'jaypeak-stateside',
    name: 'Jay Peak — Stateside',
    mountain: 'Jay Peak',
    url: 'https://b15.hdrelay.com/camera/6526ffaa1c3bd6b512d2585d/snapshot',
    type: 'image',
    region: 'Vermont',
    provider: 'HDRelay',
    latitude: 44.937,
    longitude: -72.5079,
  },
  {
    id: 'jaypeak-summit',
    name: 'Jay Peak — Summit',
    mountain: 'Jay Peak',
    url: 'https://storage.googleapis.com/prism-cam-00058/1080-watermark.jpg',
    type: 'image',
    region: 'Vermont',
    provider: 'Prism',
    latitude: 44.937,
    longitude: -72.5079,
  },
  {
    id: 'okemo',
    home: true,
    name: 'Okemo — Sugar House Cam',
    mountain: 'Okemo',
    url: 'https://player.brownrice.com/snapshot/okemosugarhouse',
    type: 'image',
    region: 'Vermont',
    provider: 'Brownrice',
    latitude: 43.4012,
    longitude: -72.7184,
  },
  {
    id: 'killington-superstar',
    home: true,
    name: 'Killington — Superstar',
    mountain: 'Killington',
    url: 'https://manage.hdrelay.com/snapshot/a0de9878-d7b7-4906-9e83-536fde35c8a9?size=1082x614&f=60000',
    type: 'image',
    region: 'Vermont',
    provider: 'HDRelay',
    latitude: 43.6026,
    longitude: -72.8179,
  },
  {
    id: 'killington-north-ridge',
    name: 'Killington — North Ridge',
    mountain: 'Killington',
    url: 'https://manage.hdrelay.com/snapshot/61e3ce02-faaa-4499-a547-6574ef6fa4f6?size=1082x614&f=60000',
    type: 'image',
    region: 'Vermont',
    provider: 'HDRelay',
    latitude: 43.6026,
    longitude: -72.8179,
  },
  {
    id: 'killington-snowshed',
    name: 'Killington — Snowshed',
    mountain: 'Killington',
    url: 'https://manage.hdrelay.com/snapshot/705fdfca-9ee5-4adf-a6e5-2dbe95708c1a?size=1082x614&f=60000',
    type: 'image',
    region: 'Vermont',
    provider: 'HDRelay',
    latitude: 43.6026,
    longitude: -72.8179,
  },
  {
    id: 'killington-bear-mountain',
    name: 'Killington — Bear Mountain',
    mountain: 'Killington',
    url: 'https://manage.hdrelay.com/snapshot/48933086-3e4f-4093-818f-603f6d084c81?size=1082x614&f=60000',
    type: 'image',
    region: 'Vermont',
    provider: 'HDRelay',
    latitude: 43.6026,
    longitude: -72.8179,
  },
  {
    id: 'killington-mountain-view',
    name: 'Killington — Mountain View',
    mountain: 'Killington',
    url: 'https://manage.hdrelay.com/snapshot/5f4fb731-c591-464f-a60d-dccc968e8fa0?size=1082x614&f=60000',
    type: 'image',
    region: 'Vermont',
    provider: 'HDRelay',
    latitude: 43.6026,
    longitude: -72.8179,
  },

  // —— New York ——
  {
    id: 'hunter-main',
    home: true,
    name: 'Hunter Mountain — Base Area',
    mountain: 'Hunter Mountain',
    url: 'https://player.brownrice.com/snapshot/hunter1',
    type: 'image',
    region: 'New York',
    provider: 'Brownrice',
    latitude: 42.2026,
    longitude: -74.2332,
  },
  {
    id: 'whiteface-legacy-lodge',
    home: true,
    name: 'Whiteface — Legacy Lodge',
    mountain: 'Whiteface',
    url: 'https://manage.hdrelay.com/snapshot/56ce853a-23fc-48cc-af9b-13907ef75b9a?size=1082x614&f=60000',
    type: 'image',
    region: 'New York',
    provider: 'HDRelay',
    latitude: 44.3653,
    longitude: -73.9021,
  },

  // —— Maine ——
  {
    id: 'sugarloaf',
    home: true,
    name: 'Sugarloaf — The Beach',
    mountain: 'Sugarloaf',
    url: 'https://www.youtube.com/embed/j8VVBhJdyqY?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Maine',
    provider: 'YouTube',
    latitude: 45.0317,
    longitude: -70.3131,
  },
  {
    id: 'sunday-river-peak-lodge',
    home: true,
    name: 'Sunday River — Peak Lodge',
    mountain: 'Sunday River',
    url: 'https://www.youtube.com/embed/J98tW5YX4Z8?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Maine',
    provider: 'YouTube',
    latitude: 44.4734,
    longitude: -70.8569,
  },
  {
    id: 'sunday-river-jordan-8',
    name: 'Sunday River — Jordan 8',
    mountain: 'Sunday River',
    url: 'https://www.youtube.com/embed/AtXgvVaqy88?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Maine',
    provider: 'YouTube',
    latitude: 44.4734,
    longitude: -70.8569,
  },
  {
    id: 'sunday-river-barker-6',
    name: 'Sunday River — Barker 6',
    mountain: 'Sunday River',
    url: 'https://www.youtube.com/embed/2KZpFcnZ7ig?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Maine',
    provider: 'YouTube',
    latitude: 44.4734,
    longitude: -70.8569,
  },
];

/** Refresh interval for image-type webcams (milliseconds). Default: 5 minutes. */
export const IMAGE_REFRESH_MS = 5 * 60 * 1000;
