/**
 * Ski resort webcam configuration (North America focus).
 * - type: 'image' — direct snapshot URL (auto-refreshed)
 * - type: 'iframe' — embedded live page (Roundshot, YouTube, etc.)
 * - mountain — groups cams for powder ranking (one snow score per mountain)
 *
 * Brownrice snapshots: https://player.brownrice.com/snapshot/{streamName}
 * WEATHER: lat/long → Open-Meteo powder radar + 7-day forecast.
 */
export const RESORTS = [
  // —— Colorado ——
  {
    id: 'vail-back-bowls',
    name: 'Vail — The Back Bowls',
    mountain: 'Vail',
    url: 'https://player.brownrice.com/snapshot/vailch21',
    type: 'image',
    region: 'Colorado',
    provider: 'Brownrice',
    latitude: 39.6403,
    longitude: -106.3742,
  },
  {
    id: 'vail-blue-sky',
    name: 'Vail — Blue Sky Basin',
    mountain: 'Vail',
    url: 'https://player.brownrice.com/snapshot/vailbluesky',
    type: 'image',
    region: 'Colorado',
    provider: 'Brownrice',
    latitude: 39.6403,
    longitude: -106.3742,
  },
  {
    id: 'vail-eagles-nest',
    name: 'Vail — Eagle’s Nest',
    mountain: 'Vail',
    url: 'https://player.brownrice.com/snapshot/vaileaglesnest',
    type: 'image',
    region: 'Colorado',
    provider: 'Brownrice',
    latitude: 39.6403,
    longitude: -106.3742,
  },
  {
    id: 'beaver-creek-spruce',
    name: 'Beaver Creek — Spruce Saddle',
    mountain: 'Beaver Creek',
    url: 'https://player.brownrice.com/snapshot/bcspruce',
    type: 'image',
    region: 'Colorado',
    provider: 'Brownrice',
    latitude: 39.6042,
    longitude: -106.5165,
  },
  {
    id: 'keystone-river-run',
    name: 'Keystone — River Run',
    mountain: 'Keystone',
    url: 'https://player.brownrice.com/snapshot/keystoneriverrun',
    type: 'image',
    region: 'Colorado',
    provider: 'Brownrice',
    latitude: 39.6069,
    longitude: -105.9542,
  },
  {
    id: 'keystone-north-peak',
    name: 'Keystone — North Peak',
    mountain: 'Keystone',
    url: 'https://player.brownrice.com/snapshot/keystonenorthpeak',
    type: 'image',
    region: 'Colorado',
    provider: 'Brownrice',
    latitude: 39.6069,
    longitude: -105.9542,
  },
  {
    id: 'crested-butte-base',
    name: 'Crested Butte — Base',
    mountain: 'Crested Butte',
    url: 'https://player.brownrice.com/snapshot/crestedbuttebase',
    type: 'image',
    region: 'Colorado',
    provider: 'Brownrice',
    latitude: 38.8997,
    longitude: -106.9658,
  },
  {
    id: 'aspen-roundshot',
    name: 'Aspen Mountain — Roundshot',
    mountain: 'Aspen',
    url: 'https://aspen.roundshot.com/',
    type: 'iframe',
    region: 'Colorado',
    provider: 'Roundshot',
    latitude: 39.1867,
    longitude: -106.8175,
  },
  {
    id: 'arapaho-basin-base',
    name: 'Arapahoe Basin — Base Area',
    mountain: 'Arapahoe Basin',
    url: 'https://ftp.purchus.io/wwwroot/abasin/webcam/abasincam1001m.jpg',
    type: 'image',
    region: 'Colorado',
    provider: 'A-Basin',
    latitude: 39.6425,
    longitude: -105.8717,
  },
  {
    id: 'arapaho-basin-zuma',
    name: 'Arapahoe Basin — Zuma',
    mountain: 'Arapahoe Basin',
    url: 'https://ftp.purchus.io/wwwroot/abasin/webcam/abasincam5.jpg',
    type: 'image',
    region: 'Colorado',
    provider: 'A-Basin',
    latitude: 39.6425,
    longitude: -105.8717,
  },
  {
    id: 'copper-cam-1',
    name: 'Copper Mountain — Cam 1',
    mountain: 'Copper Mountain',
    url: 'https://manage.hdrelay.com/snapshot/fb469125-f1f3-459f-aeb4-98cb674e395f?size=1082x614&f=60000',
    type: 'image',
    region: 'Colorado',
    provider: 'HDRelay',
    latitude: 39.5022,
    longitude: -106.1497,
  },
  {
    id: 'copper-cam-2',
    name: 'Copper Mountain — Cam 2',
    mountain: 'Copper Mountain',
    url: 'https://manage.hdrelay.com/snapshot/59703a85-67d3-4825-9f33-b8244569af43?size=1082x614&f=60000',
    type: 'image',
    region: 'Colorado',
    provider: 'HDRelay',
    latitude: 39.5022,
    longitude: -106.1497,
  },
  {
    id: 'steamboat-square',
    name: 'Steamboat — Square Cam',
    mountain: 'Steamboat',
    url: 'https://www.youtube.com/embed/2UJDLWcSADk?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Colorado',
    provider: 'YouTube',
    latitude: 40.4572,
    longitude: -106.8045,
  },
  {
    id: 'steamboat-thunderhead',
    name: 'Steamboat — Thunderhead',
    mountain: 'Steamboat',
    url: 'https://www.youtube.com/embed/nfTQNv3jdSQ?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Colorado',
    provider: 'YouTube',
    latitude: 40.4572,
    longitude: -106.8045,
  },
  {
    id: 'winter-park-base',
    name: 'Winter Park — Base Cam',
    mountain: 'Winter Park',
    url: 'https://www.youtube.com/embed/vyWAzJAWv4w?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Colorado',
    provider: 'YouTube',
    latitude: 39.8868,
    longitude: -105.7625,
  },
  {
    id: 'winter-park-snow-stake',
    name: 'Winter Park — Snow Stake',
    mountain: 'Winter Park',
    url: 'https://www.youtube.com/embed/_wOIgFEMypY?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Colorado',
    provider: 'YouTube',
    latitude: 39.8868,
    longitude: -105.7625,
  },

  // —— California / Nevada (Tahoe) ——
  {
    id: 'heavenly-tram',
    name: 'Heavenly — Tram',
    mountain: 'Heavenly',
    url: 'https://player.brownrice.com/snapshot/heavenlytram',
    type: 'image',
    region: 'California',
    provider: 'Brownrice',
    latitude: 38.9353,
    longitude: -119.9395,
  },
  {
    id: 'heavenly-midstation',
    name: 'Heavenly — Mid Station',
    mountain: 'Heavenly',
    url: 'https://player.brownrice.com/snapshot/heavenlymidstation',
    type: 'image',
    region: 'California',
    provider: 'Brownrice',
    latitude: 38.9353,
    longitude: -119.9395,
  },
  {
    id: 'northstar-pluto',
    name: 'Northstar — Pluto',
    mountain: 'Northstar',
    url: 'https://player.brownrice.com/snapshot/northstarspluto',
    type: 'image',
    region: 'California',
    provider: 'Brownrice',
    latitude: 39.2746,
    longitude: -120.1211,
  },
  {
    id: 'northstar-village',
    name: 'Northstar — Village',
    mountain: 'Northstar',
    url: 'https://player.brownrice.com/snapshot/northstarvillage',
    type: 'image',
    region: 'California',
    provider: 'Brownrice',
    latitude: 39.2746,
    longitude: -120.1211,
  },
  {
    id: 'palisades-alpine',
    name: 'Palisades Tahoe — Alpine',
    mountain: 'Palisades Tahoe',
    url: 'https://palisadestahoe.roundshot.com/alpine/',
    type: 'iframe',
    region: 'California',
    provider: 'Roundshot',
    latitude: 39.197,
    longitude: -120.2356,
  },
  {
    id: 'palisades-silverado',
    name: 'Palisades Tahoe — Silverado',
    mountain: 'Palisades Tahoe',
    url: 'https://palisadestahoe.roundshot.com/silverado/',
    type: 'iframe',
    region: 'California',
    provider: 'Roundshot',
    latitude: 39.197,
    longitude: -120.2356,
  },
  {
    id: 'mammoth-unbound',
    name: 'Mammoth — Unbound Main Park',
    mountain: 'Mammoth Mountain',
    url: 'https://media.mammothresorts.com/mmsa/mammoth/cams/Unbound_Main_Park_1_1280x720.jpg',
    type: 'image',
    region: 'California',
    provider: 'Mammoth Resorts',
    latitude: 37.6308,
    longitude: -119.0326,
  },
  {
    id: 'mammoth-top-sierra',
    name: 'Mammoth — Top of Sierra',
    mountain: 'Mammoth Mountain',
    url: 'https://media.mammothresorts.com/mmsa/mammoth/cams/Top_Of_Sierra_1_1280x720.jpg',
    type: 'image',
    region: 'California',
    provider: 'Mammoth Resorts',
    latitude: 37.6308,
    longitude: -119.0326,
  },

  // —— Utah ——
  {
    id: 'snowbird-hidden-peak',
    name: 'Snowbird — Hidden Peak 360',
    mountain: 'Snowbird',
    url: 'https://snowbird.roundshot.com/tv',
    type: 'iframe',
    region: 'Utah',
    provider: 'Roundshot',
    latitude: 40.583,
    longitude: -111.657,
  },
  {
    id: 'solitude-base',
    name: 'Solitude — Base',
    mountain: 'Solitude',
    url: 'https://player.brownrice.com/snapshot/kirkwoodcornice',
    type: 'image',
    region: 'Utah',
    provider: 'Brownrice',
    latitude: 40.6198,
    longitude: -111.5933,
  },

  // —— New Mexico ——
  {
    id: 'taos-base',
    name: 'Taos — Base',
    mountain: 'Taos Ski Valley',
    url: 'https://player.brownrice.com/snapshot/tsv',
    type: 'image',
    region: 'New Mexico',
    provider: 'Brownrice',
    latitude: 36.5957,
    longitude: -105.4505,
  },
  {
    id: 'taos-highline',
    name: 'Taos — Highline Ridge',
    mountain: 'Taos Ski Valley',
    url: 'https://player.brownrice.com/snapshot/tsvridge',
    type: 'image',
    region: 'New Mexico',
    provider: 'Brownrice',
    latitude: 36.5957,
    longitude: -105.4505,
  },
  {
    id: 'taos-kachina',
    name: 'Taos — Kachina Peak',
    mountain: 'Taos Ski Valley',
    url: 'https://player.brownrice.com/snapshot/tsvlonestar',
    type: 'image',
    region: 'New Mexico',
    provider: 'Brownrice',
    latitude: 36.5957,
    longitude: -105.4505,
  },

  // —— Wyoming ——
  {
    id: 'jackson-hole-summit',
    name: 'Jackson Hole — Summit',
    mountain: 'Jackson Hole',
    url: 'https://jacksonhole.roundshot.com/summit/',
    type: 'iframe',
    region: 'Wyoming',
    provider: 'Roundshot',
    latitude: 43.5875,
    longitude: -110.8278,
  },
  {
    id: 'jackson-hole-tram-station',
    name: 'Jackson Hole — Tram Station',
    mountain: 'Jackson Hole',
    url: 'https://cams.jacksonhole.com/webcam/trambase.jpg',
    type: 'image',
    region: 'Wyoming',
    provider: 'Jackson Hole',
    latitude: 43.5875,
    longitude: -110.8278,
  },

  // —— Montana ——
  {
    id: 'big-sky-lone-peak-tram',
    name: 'Big Sky — Lone Peak Tram',
    mountain: 'Big Sky',
    url: 'https://camstreamer.com/embed/hcsmYlCWjirEU86zfXwaFGyX7w6GL3xJ3M3TkbZf?enablejsapi=1&rel=0&modestbranding=1&playsinline=1',
    type: 'iframe',
    region: 'Montana',
    provider: 'Camstreamer',
    latitude: 45.285,
    longitude: -111.4017,
  },
  {
    id: 'big-sky-everetts-8800',
    name: 'Big Sky — Everett’s 8800',
    mountain: 'Big Sky',
    url: 'https://camstreamer.com/embed/dmy0fkeL3LXtkQnzlK5Td1QrVGSt08aM8IVVmE08?enablejsapi=1&rel=0&modestbranding=1&playsinline=1',
    type: 'iframe',
    region: 'Montana',
    provider: 'Camstreamer',
    latitude: 45.285,
    longitude: -111.4017,
  },
  {
    id: 'big-sky-golf-course',
    name: 'Big Sky — Golf Course',
    mountain: 'Big Sky',
    url: 'https://camstreamer.com/embed/bvRmCc5qmXcMEJ02xMlIAL4cg3291Tfj0pzIp9tW?enablejsapi=1&rel=0&modestbranding=1&playsinline=1',
    type: 'iframe',
    region: 'Montana',
    provider: 'Camstreamer',
    latitude: 45.285,
    longitude: -111.4017,
  },

  // —— Washington ——
  {
    id: 'stevens-pass-jupiter',
    name: 'Stevens Pass — Jupiter',
    mountain: 'Stevens Pass',
    url: 'https://player.brownrice.com/snapshot/stevenspassjupiter',
    type: 'image',
    region: 'Washington',
    provider: 'Brownrice',
    latitude: 47.746,
    longitude: -121.088,
  },
  {
    id: 'stevens-pass-snowstake',
    name: 'Stevens Pass — Snow Stake',
    mountain: 'Stevens Pass',
    url: 'https://player.brownrice.com/snapshot/stevenspasssnowstake',
    type: 'image',
    region: 'Washington',
    provider: 'Brownrice',
    latitude: 47.746,
    longitude: -121.088,
  },

  // —— Alberta (SkiBig3: Lake Louise, Banff Sunshine, Mt. Norquay) ——
  {
    id: 'lake-louise-1',
    name: 'Lake Louise — Gondola Top',
    mountain: 'Lake Louise',
    url: 'https://cams.skilouise.com/cam1.jpg',
    type: 'image',
    region: 'Alberta',
    provider: 'Lake Louise',
    latitude: 51.4254,
    longitude: -116.1773,
  },
  {
    id: 'lake-louise-2',
    name: 'Lake Louise — Base Area',
    mountain: 'Lake Louise',
    url: 'https://cams.skilouise.com/cam2.jpg',
    type: 'image',
    region: 'Alberta',
    provider: 'Lake Louise',
    latitude: 51.4254,
    longitude: -116.1773,
  },
  {
    id: 'lake-louise-3',
    name: 'Lake Louise — Ptarmigan',
    mountain: 'Lake Louise',
    url: 'https://cams.skilouise.com/cam3.jpg',
    type: 'image',
    region: 'Alberta',
    provider: 'Lake Louise',
    latitude: 51.4254,
    longitude: -116.1773,
  },
  {
    id: 'lake-louise-5',
    name: 'Lake Louise — Ptarmigan Top Distant',
    mountain: 'Lake Louise',
    url: 'https://cams.skilouise.com/cam5.jpg',
    type: 'image',
    region: 'Alberta',
    provider: 'Lake Louise',
    latitude: 51.4254,
    longitude: -116.1773,
  },
  {
    id: 'lake-louise-paradise',
    name: 'Lake Louise — Paradise',
    mountain: 'Lake Louise',
    url: 'https://cams.skilouise.com/cam8.jpg',
    type: 'image',
    region: 'Alberta',
    provider: 'Lake Louise',
    latitude: 51.4254,
    longitude: -116.1773,
  },
  {
    id: 'banff-sunshine-standish',
    name: 'Banff Sunshine — Standish Express',
    mountain: 'Banff Sunshine',
    url: 'https://cameras.skibanff.com/dynamic/15m',
    type: 'image',
    region: 'Alberta',
    provider: 'Banff Sunshine',
    latitude: 51.0783,
    longitude: -115.7786,
  },
  {
    id: 'banff-sunshine-strawberry',
    name: 'Banff Sunshine — Strawberry Express',
    mountain: 'Banff Sunshine',
    url: 'https://cameras.skibanff.com/dynamic/14m',
    type: 'image',
    region: 'Alberta',
    provider: 'Banff Sunshine',
    latitude: 51.0783,
    longitude: -115.7786,
  },
  {
    id: 'banff-sunshine-aurora',
    name: 'Banff Sunshine — Aurora Cam',
    mountain: 'Banff Sunshine',
    url: 'https://cameras.skibanff.com/dynamic/10m',
    type: 'image',
    region: 'Alberta',
    provider: 'Banff Sunshine',
    latitude: 51.0783,
    longitude: -115.7786,
  },
  {
    id: 'banff-sunshine-assiniboine',
    name: 'Banff Sunshine — Mount Assiniboine',
    mountain: 'Banff Sunshine',
    url: 'https://cameras.skibanff.com/dynamic/17m',
    type: 'image',
    region: 'Alberta',
    provider: 'Banff Sunshine',
    latitude: 51.0783,
    longitude: -115.7786,
  },
  {
    id: 'mt-norquay-cascade',
    name: 'Mt. Norquay — Cascade',
    mountain: 'Mt. Norquay',
    url: 'https://banffnorquay.com/webcam-images/winter/CascadeCam/cascade.jpg',
    type: 'image',
    region: 'Alberta',
    provider: 'Mt. Norquay',
    latitude: 51.2047,
    longitude: -115.5986,
  },
  {
    id: 'mt-norquay-sundance',
    name: 'Mt. Norquay — Sundance',
    mountain: 'Mt. Norquay',
    url: 'https://banffnorquay.com/webcam-images/winter/SundanceCam/sundance.jpg',
    type: 'image',
    region: 'Alberta',
    provider: 'Mt. Norquay',
    latitude: 51.2047,
    longitude: -115.5986,
  },

  // —— British Columbia ——
  {
    id: 'whistler-roundhouse',
    name: 'Whistler — Roundhouse Lodge',
    mountain: 'Whistler Blackcomb',
    url: 'https://player.brownrice.com/snapshot/whistlerroundhouse',
    type: 'image',
    region: 'British Columbia',
    provider: 'Brownrice',
    latitude: 50.1163,
    longitude: -122.9574,
  },
  {
    id: 'whistler-peak',
    name: 'Whistler — Peak',
    mountain: 'Whistler Blackcomb',
    url: 'https://player.brownrice.com/snapshot/whistlerpeak',
    type: 'image',
    region: 'British Columbia',
    provider: 'Brownrice',
    latitude: 50.1163,
    longitude: -122.9574,
  },
  {
    id: 'whistler-creekside',
    name: 'Whistler — Creekside',
    mountain: 'Whistler Blackcomb',
    url: 'https://player.brownrice.com/snapshot/whistlercreekside',
    type: 'image',
    region: 'British Columbia',
    provider: 'Brownrice',
    latitude: 50.1163,
    longitude: -122.9574,
  },
  {
    id: 'whistler-blackcomb',
    name: 'Blackcomb — Base',
    mountain: 'Whistler Blackcomb',
    url: 'https://player.brownrice.com/snapshot/whistlerblackcomb',
    type: 'image',
    region: 'British Columbia',
    provider: 'Brownrice',
    latitude: 50.1163,
    longitude: -122.9574,
  },
  {
    id: 'whistler-7th-heaven',
    name: 'Blackcomb — 7th Heaven',
    mountain: 'Whistler Blackcomb',
    url: 'https://player.brownrice.com/snapshot/whistler7thheaven',
    type: 'image',
    region: 'British Columbia',
    provider: 'Brownrice',
    latitude: 50.1163,
    longitude: -122.9574,
  },
  {
    id: 'kicking-horse-top',
    name: 'Kicking Horse — Top (Stairway)',
    mountain: 'Kicking Horse',
    url: 'https://www.youtube.com/embed/DA5VYgThjvM?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'British Columbia',
    provider: 'YouTube (Kicking Horse)',
    latitude: 51.2992,
    longitude: -117.0536,
  },
  {
    id: 'kicking-horse-base',
    name: 'Kicking Horse — Base',
    mountain: 'Kicking Horse',
    url: 'https://www.youtube.com/embed/3blOIv-En04?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'British Columbia',
    provider: 'YouTube (Kicking Horse)',
    latitude: 51.2992,
    longitude: -117.0536,
  },
  {
    id: 'revelstoke-village',
    name: 'Revelstoke — Village',
    mountain: 'Revelstoke',
    url: 'https://relay.ozolio.com/pub.api?cmd=embed&oid=EMB_PVWK000010B0',
    type: 'iframe',
    region: 'British Columbia',
    provider: 'Ozolio',
    latitude: 50.9581,
    longitude: -118.1637,
  },
  {
    id: 'revelstoke-skywalk',
    name: 'Revelstoke — Skywalk',
    mountain: 'Revelstoke',
    url: 'https://relay.ozolio.com/pub.api?cmd=embed&oid=EMB_SCDV000013E4',
    type: 'iframe',
    region: 'British Columbia',
    provider: 'Ozolio',
    latitude: 50.9581,
    longitude: -118.1637,
  },
  {
    id: 'revelstoke-stoke',
    name: 'Revelstoke — Top of Stoke Chair',
    mountain: 'Revelstoke',
    url: 'https://relay.ozolio.com/pub.api?cmd=embed&oid=EMB_KPMC000010BF',
    type: 'iframe',
    region: 'British Columbia',
    provider: 'Ozolio',
    latitude: 50.9581,
    longitude: -118.1637,
  },
  {
    id: 'revelstoke-upper-gondola',
    name: 'Revelstoke — Top of Upper Gondola',
    mountain: 'Revelstoke',
    url: 'https://relay.ozolio.com/pub.api?cmd=embed&oid=EMB_NDZZ000010B5',
    type: 'iframe',
    region: 'British Columbia',
    provider: 'Ozolio',
    latitude: 50.9581,
    longitude: -118.1637,
  },

  // —— Vermont ——
  {
    id: 'stowe-village',
    name: 'Stowe — Village',
    mountain: 'Stowe',
    url: 'https://player.brownrice.com/snapshot/stowevillage',
    type: 'image',
    region: 'Vermont',
    provider: 'Brownrice',
    latitude: 44.5313,
    longitude: -72.7814,
  },
  {
    id: 'mount-snow-base',
    name: 'Mount Snow — Base',
    mountain: 'Mount Snow',
    url: 'https://player.brownrice.com/snapshot/mountsnowbase',
    type: 'image',
    region: 'Vermont',
    provider: 'Brownrice',
    latitude: 42.9084,
    longitude: -72.8637,
  },
  {
    id: 'sugarbush',
    name: 'Sugarbush — Gate House',
    mountain: 'Sugarbush',
    url: 'https://www.youtube.com/embed/jhCh3dsEv-M?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Vermont',
    provider: 'YouTube',
    latitude: 44.1353,
    longitude: -72.9084,
  },
  {
    id: 'jaypeak',
    name: 'Jay Peak — Tramside',
    mountain: 'Jay Peak',
    url: 'https://b15.hdrelay.com/camera/6526fd5a071b19b5189bb07b/snapshot',
    type: 'image',
    region: 'Vermont',
    provider: 'HDRelay',
    latitude: 44.937,
    longitude: -72.5079,
  },
  {
    id: 'okemo',
    name: 'Okemo — Sugar House Cam',
    mountain: 'Okemo',
    url: 'https://player.brownrice.com/snapshot/okemosugarhouse',
    type: 'image',
    region: 'Vermont',
    provider: 'Brownrice',
    latitude: 43.4012,
    longitude: -72.7184,
  },
  {
    id: 'killington',
    name: 'Killington — North Ridge',
    mountain: 'Killington',
    url: 'https://manage.hdrelay.com/snapshot/61e3ce02-faaa-4499-a547-6574ef6fa4f6?size=1082x614&f=60000',
    type: 'image',
    region: 'Vermont',
    provider: 'HDRelay',
    latitude: 43.6026,
    longitude: -72.8179,
  },

  // —— New York ——
  {
    id: 'hunter-main',
    name: 'Hunter Mountain — Base Area',
    mountain: 'Hunter Mountain',
    url: 'https://player.brownrice.com/snapshot/hunter1',
    type: 'image',
    region: 'New York',
    provider: 'Brownrice',
    latitude: 42.2026,
    longitude: -74.2332,
  },
  {
    id: 'whiteface',
    name: 'Whiteface — Lake Placid',
    mountain: 'Whiteface',
    url: 'https://imgproxy.windy.com/_/preview/plain/current/1748724797/original.jpg',
    type: 'image',
    region: 'New York',
    provider: 'Windy',
    latitude: 44.3653,
    longitude: -73.9021,
  },
  {
    id: 'whiteface-legacy-lodge',
    name: 'Whiteface — Legacy Lodge',
    mountain: 'Whiteface',
    url: 'https://manage.hdrelay.com/snapshot/56ce853a-23fc-48cc-af9b-13907ef75b9a?size=1082x614&f=60000',
    type: 'image',
    region: 'New York',
    provider: 'HDRelay',
    latitude: 44.3653,
    longitude: -73.9021,
  },

  // —— Maine ——
  {
    id: 'sugarloaf',
    name: 'Sugarloaf — The Beach',
    mountain: 'Sugarloaf',
    url: 'https://www.youtube.com/embed/j8VVBhJdyqY?autoplay=1&mute=1&rel=0',
    type: 'iframe',
    region: 'Maine',
    provider: 'YouTube',
    latitude: 45.0317,
    longitude: -70.3131,
  },
];

/** Refresh interval for image-type webcams (milliseconds). Default: 5 minutes. */
export const IMAGE_REFRESH_MS = 5 * 60 * 1000;
